//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skills4Hire
{
    using System;
    using System.Collections.Generic;
    
    public partial class deletedmembership
    {
        public int Id { get; set; }
        public string userName { get; set; }
        public string email { get; set; }
        public string leavingReason { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
