//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skills4Hire
{
    using System;
    using System.Collections.Generic;
    
    public partial class guardianjob
    {
        public int Id { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public string Experience { get; set; }
        public string Qualification { get; set; }
        public string HowToApply { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> Publish { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> DateTimeEdited { get; set; }
    }
}
