//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skills4Hire
{
    using System;
    using System.Collections.Generic;
    
    public partial class indprofile
    {
        public int idIndProfile { get; set; }
        public string FullName { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> Age { get; set; }
        public string ContactNo { get; set; }
        public string EmailAddr { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> LocalGovtId { get; set; }
        public string Town { get; set; }
        public Nullable<int> SkillsId { get; set; }
        public string SkillsSpecific { get; set; }
        public string JobExperience { get; set; }
        public string Qualification { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Publish { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<System.DateTime> GoldSubExpire { get; set; }
        public Nullable<bool> IsGoldMember { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual gender gender { get; set; }
        public virtual localgovtofresidence localgovtofresidence { get; set; }
        public virtual skill skill { get; set; }
        public virtual stateofresidence stateofresidence { get; set; }
    }
}
