//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skills4Hire
{
    using System;
    using System.Collections.Generic;
    
    public partial class mysavedjob
    {
        public int Id { get; set; }
        public string sJobTitle { get; set; }
        public Nullable<int> sJobId { get; set; }
        public Nullable<System.DateTime> DateSaved { get; set; }
        public string SavedBy { get; set; }
    }
}
