//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skills4Hire
{
    using System;
    using System.Collections.Generic;
    
    public partial class profileflag
    {
        public int Id { get; set; }
        public string ProfileUrl { get; set; }
        public string FlagReason { get; set; }
        public Nullable<System.DateTime> DateTimeReported { get; set; }
        public string ReportedBy { get; set; }
    }
}
