//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skills4Hire
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class skillsforhireEntities : DbContext
    {
        public skillsforhireEntities()
            : base("name=skillsforhireEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<budget> budgets { get; set; }
        public virtual DbSet<deletedmembership> deletedmemberships { get; set; }
        public virtual DbSet<gender> genders { get; set; }
        public virtual DbSet<indprofile> indprofiles { get; set; }
        public virtual DbSet<jobprofile> jobprofiles { get; set; }
        public virtual DbSet<jobstatu> jobstatus { get; set; }
        public virtual DbSet<localgovtofresidence> localgovtofresidences { get; set; }
        public virtual DbSet<skill> skills { get; set; }
        public virtual DbSet<starttime> starttimes { get; set; }
        public virtual DbSet<stateofresidence> stateofresidences { get; set; }
        public virtual DbSet<mysavedjob> mysavedjobs { get; set; }
        public virtual DbSet<jobpostflag> jobpostflags { get; set; }
        public virtual DbSet<profileflag> profileflags { get; set; }
        public virtual DbSet<bankpaymentrequest> bankpaymentrequests { get; set; }
        public virtual DbSet<guardianjob> guardianjobs { get; set; }
    }
}
